name: auth_app
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.3
  cupertino_icons: ^1.0.0
  equatable: ^1.2.5
  firebase_auth: ^0.18.3
  firebase_database: ^4.3.0
  flutter_bloc: ^6.1.1
  font_awesome_flutter: ^8.10.0
  formz: ^0.3.2
  google_sign_in: ^4.5.6
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - google_g.png
